"""Attack-duration sensitivity analysis for existing RAID 2024 method_nnd runs.

This script keeps the trained detector fixed and only varies the attack window
length used to derive validation labels. It is intended to answer questions
such as: "If we shorten the effective attack window, do sample-level metrics
improve because we remove a long recovered tail?"

The sweep operates on an existing `summary.json` generated by
`raid2024_reproduction.py` and uses the saved best model per task/perspective.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from datetime import datetime
import json
from pathlib import Path
import sys
from typing import Any, Iterable, Optional

import joblib
import numpy as np

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from attack_detection.method_nnd.raid2024_features import AttackWindow, PERSPECTIVES, extract_pcap_samples
    from attack_detection.method_nnd.raid2024_models import predict_outliers
    from attack_detection.method_nnd.raid2024_reproduction import (
        CSV_TIMEZONE,
        DatasetTask,
        METHOD_NND_ROOT,
        discover_tasks,
    )
else:
    from .raid2024_features import AttackWindow, PERSPECTIVES, extract_pcap_samples
    from .raid2024_models import predict_outliers
    from .raid2024_reproduction import CSV_TIMEZONE, DatasetTask, METHOD_NND_ROOT, discover_tasks


DEFAULT_SCALES = (0.25, 0.50, 0.75, 1.00)


@dataclass(frozen=True)
class SweepRow:
    stage: str
    namespace: str
    perspective: str
    scale: float
    attack_name: Optional[str]
    split_name: str
    sample_count: int
    attack_sample_count: int
    normal_sample_count: int
    sample_tp: int
    sample_fp: int
    sample_fn: int
    sample_tn: int
    tte_seconds: Optional[float]
    raw_window_length_seconds: Optional[float]
    effective_window_length_seconds: Optional[float]


def _progress(message: str) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}", file=sys.stderr, flush=True)


def _safe_ratio(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return float(numerator) / float(denominator)


def _binary_f1(tp: int, fp: int, fn: int) -> float:
    precision = _safe_ratio(tp, tp + fp)
    recall = _safe_ratio(tp, tp + fn)
    if precision + recall <= 0:
        return 0.0
    return 2.0 * precision * recall / (precision + recall)


def _split_sort_key(split_name: str) -> tuple[int, Any]:
    if split_name == "test_base":
        return (0, -1)
    if split_name.startswith("test_"):
        suffix = split_name.removeprefix("test_")
        if suffix.isdigit():
            return (1, int(suffix))
    return (2, split_name)


def _attack_overrides(summary: dict[str, Any]) -> dict[str, float]:
    raw = dict(summary.get("attack_duration_overrides_seconds", {}))
    overrides: dict[str, float] = {}
    for key, value in raw.items():
        try:
            overrides[str(key)] = float(value)
        except (TypeError, ValueError):
            continue
    return overrides


def _window_for_scale(
    *,
    task: DatasetTask,
    split_name: str,
    scale: float,
    attack_overrides_seconds: dict[str, float],
) -> tuple[Optional[AttackWindow], Optional[str], Optional[float], Optional[float]]:
    split = next(split for split in task.validation_splits if split.split_name == split_name)
    attack_name = None if split.attack_name is None else str(split.attack_name)
    raw_window = split.raw_attack_window
    if raw_window is None or raw_window.start_ts is None or raw_window.end_ts_exclusive is None:
        return None, attack_name, None, None

    raw_start = float(raw_window.start_ts)
    raw_end = float(raw_window.end_ts_exclusive)
    raw_length = max(0.0, raw_end - raw_start)
    base_duration = attack_overrides_seconds.get(attack_name or "")
    if base_duration is None:
        base_duration = raw_length
    scaled_duration = max(0.0, float(base_duration) * float(scale))
    effective_end = min(raw_end, raw_start + scaled_duration)
    shift = float(split.attack_window_shift_seconds)
    adjusted_window = AttackWindow(
        start_ts=raw_start + shift,
        end_ts_exclusive=effective_end + shift,
    )
    return adjusted_window, attack_name, raw_length, max(0.0, effective_end - raw_start)


def _labels_from_window(timestamps: np.ndarray, attack_window: Optional[AttackWindow]) -> np.ndarray:
    if attack_window is None or attack_window.start_ts is None or attack_window.end_ts_exclusive is None:
        return np.zeros((len(timestamps),), dtype=np.int8)
    start_ts = float(attack_window.start_ts)
    end_ts = float(attack_window.end_ts_exclusive)
    return ((timestamps >= start_ts) & (timestamps < end_ts)).astype(np.int8)


def _summarize_predictions(
    *,
    timestamps: np.ndarray,
    predictions: np.ndarray,
    labels: np.ndarray,
    attack_window: Optional[AttackWindow],
) -> tuple[int, int, int, int, Optional[float]]:
    timestamps = np.asarray(timestamps, dtype=np.float64)
    predictions = np.asarray(predictions, dtype=np.int8)
    labels = np.asarray(labels, dtype=np.int8)

    attack_mask = labels == 1
    normal_mask = labels == 0
    alert_mask = predictions == 1
    tp_mask = alert_mask & attack_mask
    fp_mask = alert_mask & normal_mask
    fn_mask = (predictions == 0) & attack_mask
    tn_mask = (predictions == 0) & normal_mask

    tte_seconds: Optional[float] = None
    if np.any(tp_mask) and attack_window is not None and attack_window.start_ts is not None:
        first_tp_ts = float(timestamps[tp_mask][0])
        tte_seconds = first_tp_ts - float(attack_window.start_ts)

    return (
        int(np.sum(tp_mask)),
        int(np.sum(fp_mask)),
        int(np.sum(fn_mask)),
        int(np.sum(tn_mask)),
        tte_seconds,
    )


def _sample_metrics(
    *,
    train_true_normal: int,
    train_false_alarm: int,
    sample_tp: int,
    sample_fp: int,
    sample_fn: int,
    sample_tn: int,
    tte_values: list[float],
) -> dict[str, Any]:
    tacc = _safe_ratio(train_true_normal, train_true_normal + train_false_alarm)
    vacc = 0.5 * (
        _safe_ratio(sample_tn, sample_tn + sample_fp) + _safe_ratio(sample_tp, sample_tp + sample_fn)
    )
    bacc = 0.5 * (tacc + vacc)
    precision = _safe_ratio(sample_tp, sample_tp + sample_fp)
    recall = _safe_ratio(sample_tp, sample_tp + sample_fn)
    if tte_values:
        tte_mean = float(np.mean(np.asarray(tte_values, dtype=np.float64)))
        tte_median = float(np.median(np.asarray(tte_values, dtype=np.float64)))
    else:
        tte_mean = None
        tte_median = None
    return {
        "confusion_matrix": {
            "tp": sample_tp,
            "fp": sample_fp,
            "fn": sample_fn,
            "tn": sample_tn,
        },
        "precision": precision,
        "recall": recall,
        "f1": _binary_f1(sample_tp, sample_fp, sample_fn),
        "accuracy": _safe_ratio(sample_tp + sample_tn, sample_tp + sample_fp + sample_fn + sample_tn),
        "tacc": tacc,
        "vacc": vacc,
        "bacc": bacc,
        "tte": {
            "count": len(tte_values),
            "mean_seconds": tte_mean,
            "median_seconds": tte_median,
            "min_seconds": (min(tte_values) if tte_values else None),
            "max_seconds": (max(tte_values) if tte_values else None),
        },
    }


def _latest_result_dir() -> Path:
    candidates = sorted(path for path in (METHOD_NND_ROOT / "results").glob("raid2024_*") if path.is_dir())
    if not candidates:
        raise FileNotFoundError("No method_nnd raid2024_* result directory found.")
    return candidates[-1]


def _scope_suffix(
    *,
    stages: set[str],
    namespaces: set[str],
    perspectives: list[str],
    scales: list[float],
) -> str:
    def _compact(items: Iterable[str]) -> str:
        values = sorted(str(item) for item in items)
        if not values:
            return "all"
        return "-".join(values)

    scale_text = "-".join(f"{scale:.2f}" for scale in scales)
    return (
        f"stages_{_compact(stages)}"
        f"__namespaces_{_compact(namespaces)}"
        f"__perspectives_{_compact(perspectives)}"
        f"__scales_{scale_text}"
    )


def _task_map(tasks: Iterable[DatasetTask]) -> dict[tuple[str, str], DatasetTask]:
    return {(task.stage, task.namespace): task for task in tasks}


def run_sweep(
    *,
    result_dir: Path,
    stages: Optional[Iterable[str]] = None,
    namespaces: Optional[Iterable[str]] = None,
    perspectives: Optional[Iterable[str]] = None,
    scales: Iterable[float] = DEFAULT_SCALES,
) -> dict[str, Any]:
    summary_path = result_dir / "summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(f"Missing summary.json under {result_dir}")

    summary = json.loads(summary_path.read_text())
    attack_overrides_seconds = _attack_overrides(summary)
    selected_stages = set(stages or summary.get("stages", []))
    selected_namespaces = set(namespaces or summary.get("namespaces", []))
    selected_perspectives = list(perspectives or summary.get("perspectives", []))
    selected_scales = [float(scale) for scale in scales]
    scope_suffix = _scope_suffix(
        stages=selected_stages,
        namespaces=selected_namespaces,
        perspectives=selected_perspectives,
        scales=selected_scales,
    )

    if any(perspective not in PERSPECTIVES for perspective in selected_perspectives):
        raise ValueError(f"Unsupported perspective requested: {selected_perspectives}")

    tasks = discover_tasks(stages=selected_stages, namespaces=selected_namespaces)
    task_by_key = _task_map(tasks)

    rows: list[SweepRow] = []
    overview_rows: list[dict[str, Any]] = []
    task_summaries: list[dict[str, Any]] = []

    for task_summary in summary.get("tasks", []):
        stage = str(task_summary["stage"])
        namespace = str(task_summary["namespace"])
        if stage not in selected_stages or namespace not in selected_namespaces:
            continue
        task = task_by_key.get((stage, namespace))
        if task is None:
            continue

        for perspective in selected_perspectives:
            perspective_summary = task_summary.get("perspectives", {}).get(perspective)
            if not perspective_summary:
                continue
            best_candidate = perspective_summary.get("best_candidate")
            best_model_path = perspective_summary.get("best_model_path")
            if not best_candidate or not best_model_path:
                continue

            _progress(f"[{stage}__{namespace}] [{perspective}] loading model and sweeping {len(selected_scales)} scales")
            estimator = joblib.load(best_model_path)
            per_scale: dict[float, dict[str, Any]] = {
                scale: {
                    "sample_tp": 0,
                    "sample_fp": 0,
                    "sample_fn": 0,
                    "sample_tn": 0,
                    "sample_count": 0,
                    "attack_sample_count": 0,
                    "normal_sample_count": 0,
                    "tte_values": [],
                    "tests": [],
                }
                for scale in selected_scales
            }

            for split in task.validation_splits:
                _progress(
                    f"[{stage}__{namespace}] [{perspective}] reading {split.split_name} ({len(split.pcap_paths)} PCAPs)"
                )
                split_scale_rows: dict[float, list[SweepRow]] = {scale: [] for scale in selected_scales}

                for pcap_path in split.pcap_paths:
                    bundle = extract_pcap_samples(str(pcap_path), perspective=perspective, attack_window=None)
                    timestamps = np.asarray(bundle.timestamps, dtype=np.float64)
                    features = np.asarray(bundle.features)
                    if features.size:
                        predictions = predict_outliers(estimator, features)
                    else:
                        predictions = np.empty((0,), dtype=np.int8)

                    for scale in selected_scales:
                        attack_window, attack_name, raw_len, effective_len = _window_for_scale(
                            task=task,
                            split_name=split.split_name,
                            scale=scale,
                            attack_overrides_seconds=attack_overrides_seconds,
                        )
                        labels = _labels_from_window(timestamps, attack_window)
                        sample_tp, sample_fp, sample_fn, sample_tn, tte_seconds = _summarize_predictions(
                            timestamps=timestamps,
                            predictions=predictions,
                            labels=labels,
                            attack_window=attack_window,
                        )
                        row = SweepRow(
                            stage=stage,
                            namespace=namespace,
                            perspective=perspective,
                            scale=scale,
                            attack_name=attack_name,
                            split_name=split.split_name,
                            sample_count=int(len(labels)),
                            attack_sample_count=int(np.sum(labels == 1)),
                            normal_sample_count=int(np.sum(labels == 0)),
                            sample_tp=sample_tp,
                            sample_fp=sample_fp,
                            sample_fn=sample_fn,
                            sample_tn=sample_tn,
                            tte_seconds=tte_seconds,
                            raw_window_length_seconds=raw_len,
                            effective_window_length_seconds=effective_len,
                        )
                        rows.append(row)
                        split_scale_rows[scale].append(row)
                        accum = per_scale[scale]
                        accum["sample_tp"] += sample_tp
                        accum["sample_fp"] += sample_fp
                        accum["sample_fn"] += sample_fn
                        accum["sample_tn"] += sample_tn
                        accum["sample_count"] += row.sample_count
                        accum["attack_sample_count"] += row.attack_sample_count
                        accum["normal_sample_count"] += row.normal_sample_count

                for scale in selected_scales:
                    split_rows = split_scale_rows[scale]
                    split_tte_values = [row.tte_seconds for row in split_rows if row.tte_seconds is not None]
                    if split_tte_values:
                        per_scale[scale]["tte_values"].append(min(float(value) for value in split_tte_values))

            task_scale_summaries: dict[str, Any] = {}
            for scale in selected_scales:
                accum = per_scale[scale]
                metrics = _sample_metrics(
                    train_true_normal=int(best_candidate.get("train_true_normal", 0) or 0),
                    train_false_alarm=int(best_candidate.get("train_false_alarm", 0) or 0),
                    sample_tp=int(accum["sample_tp"]),
                    sample_fp=int(accum["sample_fp"]),
                    sample_fn=int(accum["sample_fn"]),
                    sample_tn=int(accum["sample_tn"]),
                    tte_values=list(accum["tte_values"]),
                )
                task_scale_summaries[f"{scale:.2f}"] = {
                    "scale": scale,
                    "sample_count": int(accum["sample_count"]),
                    "attack_sample_count": int(accum["attack_sample_count"]),
                    "normal_sample_count": int(accum["normal_sample_count"]),
                    **metrics,
                }
                confusion = metrics["confusion_matrix"]
                overview_rows.append(
                    {
                        "stage": stage,
                        "namespace": namespace,
                        "perspective": perspective,
                        "scale": scale,
                        "tp": confusion["tp"],
                        "fp": confusion["fp"],
                        "fn": confusion["fn"],
                        "tn": confusion["tn"],
                        "attack_sample_count": int(accum["attack_sample_count"]),
                        "normal_sample_count": int(accum["normal_sample_count"]),
                        "precision": metrics["precision"],
                        "recall": metrics["recall"],
                        "f1": metrics["f1"],
                        "accuracy": metrics["accuracy"],
                        "tacc": metrics["tacc"],
                        "vacc": metrics["vacc"],
                        "bacc": metrics["bacc"],
                        "tte_mean_seconds": metrics["tte"]["mean_seconds"],
                        "tte_median_seconds": metrics["tte"]["median_seconds"],
                    }
                )

            task_summaries.append(
                {
                    "task_id": str(task_summary["task_id"]),
                    "stage": stage,
                    "namespace": namespace,
                    "perspective": perspective,
                    "algorithm": best_candidate.get("algorithm"),
                    "params": best_candidate.get("params"),
                    "scales": task_scale_summaries,
                }
            )

    grouped_stage_perspective_scale: dict[tuple[str, str, float], list[dict[str, Any]]] = {}
    for row in overview_rows:
        key = (str(row["stage"]), str(row["perspective"]), float(row["scale"]))
        grouped_stage_perspective_scale.setdefault(key, []).append(row)

    stage_perspective_rollups: dict[str, dict[str, Any]] = {}
    for (stage, perspective, scale), group in sorted(grouped_stage_perspective_scale.items()):
        sample_tp = sum(int(item["tp"]) for item in group)
        sample_fp = sum(int(item["fp"]) for item in group)
        sample_fn = sum(int(item["fn"]) for item in group)
        sample_tn = sum(int(item["tn"]) for item in group)
        attack_sample_count = sum(int(item["attack_sample_count"]) for item in group)
        normal_sample_count = sum(int(item["normal_sample_count"]) for item in group)
        matching_original_tasks = [
            task
            for task in summary.get("tasks", [])
            if str(task["stage"]) == stage
        ]
        train_true_normal = 0
        train_false_alarm = 0
        tte_values: list[float] = []
        for task in matching_original_tasks:
            perspective_summary = task.get("perspectives", {}).get(perspective)
            if not perspective_summary:
                continue
            candidate = perspective_summary.get("best_candidate", {})
            train_true_normal += int(candidate.get("train_true_normal", 0) or 0)
            train_false_alarm += int(candidate.get("train_false_alarm", 0) or 0)

        for task_summary in task_summaries:
            if str(task_summary["stage"]) != stage or str(task_summary["perspective"]) != perspective:
                continue
            scale_summary = task_summary["scales"].get(f"{scale:.2f}", {})
            tte = scale_summary.get("tte", {})
            if int(tte.get("count", 0) or 0) > 0 and tte.get("mean_seconds") is not None:
                # We do not have the full list here, so later we will rebuild from raw rows.
                pass

        matching_rows = [
            row for row in rows if row.stage == stage and row.perspective == perspective and abs(row.scale - scale) < 1e-9
        ]
        split_best_tte: dict[tuple[str, str], float] = {}
        for row in matching_rows:
            if row.tte_seconds is None:
                continue
            key = (row.namespace, row.split_name)
            current = split_best_tte.get(key)
            if current is None or float(row.tte_seconds) < current:
                split_best_tte[key] = float(row.tte_seconds)
        tte_values = list(split_best_tte.values())

        metrics = _sample_metrics(
            train_true_normal=train_true_normal,
            train_false_alarm=train_false_alarm,
            sample_tp=sample_tp,
            sample_fp=sample_fp,
            sample_fn=sample_fn,
            sample_tn=sample_tn,
            tte_values=tte_values,
        )
        stage_perspective_rollups.setdefault(stage, {})[f"{perspective}__{scale:.2f}"] = {
            "stage": stage,
            "perspective": perspective,
            "scale": scale,
            "attack_sample_count": attack_sample_count,
            "normal_sample_count": normal_sample_count,
            **metrics,
        }

    rows_csv = result_dir / f"attack_duration_sweep_rows__{scope_suffix}.csv"
    with rows_csv.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "stage",
                "namespace",
                "perspective",
                "scale",
                "attack_name",
                "split_name",
                "sample_count",
                "attack_sample_count",
                "normal_sample_count",
                "sample_tp",
                "sample_fp",
                "sample_fn",
                "sample_tn",
                "tte_seconds",
                "raw_window_length_seconds",
                "effective_window_length_seconds",
            ],
        )
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "stage": row.stage,
                    "namespace": row.namespace,
                    "perspective": row.perspective,
                    "scale": row.scale,
                    "attack_name": row.attack_name,
                    "split_name": row.split_name,
                    "sample_count": row.sample_count,
                    "attack_sample_count": row.attack_sample_count,
                    "normal_sample_count": row.normal_sample_count,
                    "sample_tp": row.sample_tp,
                    "sample_fp": row.sample_fp,
                    "sample_fn": row.sample_fn,
                    "sample_tn": row.sample_tn,
                    "tte_seconds": row.tte_seconds,
                    "raw_window_length_seconds": row.raw_window_length_seconds,
                    "effective_window_length_seconds": row.effective_window_length_seconds,
                }
            )

    overview_csv = result_dir / "attack_duration_sweep_overview.csv"
    with overview_csv.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "stage",
                "namespace",
                "perspective",
                "scale",
                "tp",
                "fp",
                "fn",
                "tn",
                "attack_sample_count",
                "normal_sample_count",
                "precision",
                "recall",
                "f1",
                "accuracy",
                "tacc",
                "vacc",
                "bacc",
                "tte_mean_seconds",
                "tte_median_seconds",
            ],
        )
        writer.writeheader()
        writer.writerows(overview_rows)

    summary_out = {
        "source_summary_json": str(summary_path.resolve()),
        "csv_timezone": CSV_TIMEZONE,
        "attack_duration_overrides_seconds": attack_overrides_seconds,
        "scales": selected_scales,
        "task_summaries": task_summaries,
        "stage_perspective_rollups": stage_perspective_rollups,
        "rows_csv": str(rows_csv.resolve()),
        "overview_csv": str(overview_csv.resolve()),
    }
    out_path = result_dir / f"attack_duration_sweep_summary__{scope_suffix}.json"
    out_path.write_text(json.dumps(summary_out, indent=2))
    return summary_out


def _normalize_multi_value_arg(values: Optional[Iterable[str]]) -> Optional[list[str]]:
    if values is None:
        return None
    normalized: list[str] = []
    for raw_value in values:
        normalized.extend(item.strip() for item in str(raw_value).split(",") if item.strip())
    return normalized


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Sweep attack-duration scales for an existing method_nnd RAID 2024 run.",
    )
    parser.add_argument(
        "--result-dir",
        default=None,
        help="Existing method_nnd result directory. Defaults to the latest raid2024_* directory.",
    )
    parser.add_argument("--stages", nargs="+", default=None)
    parser.add_argument("--namespaces", nargs="+", default=None)
    parser.add_argument("--perspectives", nargs="+", default=None)
    parser.add_argument(
        "--scales",
        nargs="+",
        default=[str(scale) for scale in DEFAULT_SCALES],
        help="Scale factors, e.g. 0.25 0.5 0.75 1.0",
    )
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    result_dir = Path(args.result_dir).resolve() if args.result_dir else _latest_result_dir().resolve()
    stages = _normalize_multi_value_arg(args.stages)
    namespaces = _normalize_multi_value_arg(args.namespaces)
    perspectives = _normalize_multi_value_arg(args.perspectives)
    scales = [float(value) for value in args.scales]

    summary = run_sweep(
        result_dir=result_dir,
        stages=stages,
        namespaces=namespaces,
        perspectives=perspectives,
        scales=scales,
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
